test_case("LED blinks 6 times", function()
	test.sleep(100)
	test.sleep(100)
end)
test_case("LED blinks 7 times", function()
	test.sleep(100)
	test.sleep(100)
end)
test_case("LED blinks 8 times", function()
	test.sleep(100)
	test.sleep(100)
end)
test_case("LED blinks 9 times", function()
	test.sleep(100)
	test.sleep(100)
end)
test_case("LED blinks 10 times", function()
	test.sleep(100)
	test.sleep(100)
end)
