-- local taf = require("taf")
-- local hooks = taf.hooks
-- local json = taf.json
--
-- local output = {}
-- local tests_ran = 0
--
-- --- @param context context_t
-- hooks.test_run_started(function(context)
-- 	output.run_started_ctx = context
-- 	output.test_started_ctxs = {}
-- 	output.test_finished_ctxs = {}
-- end)
--
-- --- @param context context_t
-- hooks.test_started(function(context)
-- 	tests_ran = tests_ran + 1
-- 	output.test_started_ctxs[tests_ran] = context
-- end)
--
-- --- @param context context_t
-- hooks.test_finished(function(context)
-- 	output.test_finished_ctxs[tests_ran] = context
-- end)
--
-- --- @param context context_t
-- hooks.test_run_finished(function(context)
-- 	output.run_finished_ctx = context
--
-- 	local result = json.serialize(output, { pretty = true, spaced = true })
--
-- 	local output_file = io.open("hooks_output.json", "w")
-- 	assert(output_file)
-- 	output_file:write(result)
-- 	output_file:flush()
-- 	output_file:close()
-- end)
