name: Build & Test

on:
  push:
    branches: [ "master", "gh_actions" ]
  pull_request:

jobs:
  build-and-test:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Homebrew (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin"  >> "$GITHUB_PATH"
          echo "/home/linuxbrew/.linuxbrew/sbin" >> "$GITHUB_PATH"

      - name: Install dependencies
        run: |
          brew install meson json-c notcurses lua libserialport

      - name: Build & Install (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          meson setup build
          meson install -C build

      - name: Build & Install (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export PKG_CONFIG_PATH="/home/linuxbrew/.linuxbrew/lib/pkgconfig:/home/linuxbrew/.linuxbrew/share/pkgconfig"
          meson setup build
          meson install -C build

      - name: Self-Test
        run: |
          cd selftest
          taf test selftest -e

